### PR TITLE
Major rewrite that works with current Parcel and Workbox

### PR DESCRIPTION
**Pull request by selfagency**
Addresses #12 #13 and more.

### CODE REVIEW

**Comment by icetee** [comment]
@dahnielson Please deal with this.

**Comment by selfagency** [comment]
@icetee you can grab my version here https://www.npmjs.com/package/parcel-plugin-workbox-rev

**Comment by selfagency** [comment]
👍

**Comment by dahnielson** [comment]
@selfagency Thank you for the rewrite!

**Pull request merged**
